package com.gestioncredito.credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("primer nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label("segundo nombre")
	private java.lang.String segundoNombre;
	@org.kie.api.definition.type.Label("primer apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label("segundo apellido")
	private java.lang.String segundoApellido;
	@org.kie.api.definition.type.Label("tipo documento")
	private java.lang.String tipoDocumento;
	@org.kie.api.definition.type.Label("numero documento")
	private java.lang.Integer numeroDocumento;
	@org.kie.api.definition.type.Label("fecha nacimiento")
	private java.util.Date fechaNacimiento;
	@org.kie.api.definition.type.Label("direccion")
	private java.lang.String direccion;
	@org.kie.api.definition.type.Label("telefono")
	private java.lang.Integer telefono;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("salario")
	private java.lang.Integer salario;

	@org.kie.api.definition.type.Label("gastos mensuales")
	private java.lang.Integer gastosMes;

	@org.kie.api.definition.type.Label(value = "estado")
	private java.lang.String estado;

	public Persona() {
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(java.lang.String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.lang.Integer getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.lang.Integer numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.Integer telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.Integer getSalario() {
		return this.salario;
	}

	public void setSalario(java.lang.Integer salario) {
		this.salario = salario;
	}

	public java.lang.Integer getGastosMes() {
		return this.gastosMes;
	}

	public void setGastosMes(java.lang.Integer gastosMes) {
		this.gastosMes = gastosMes;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public Persona(java.lang.String primerNombre,
			java.lang.String segundoNombre, java.lang.String primerApellido,
			java.lang.String segundoApellido, java.lang.String tipoDocumento,
			java.lang.Integer numeroDocumento, java.util.Date fechaNacimiento,
			java.lang.String direccion, java.lang.Integer telefono,
			java.lang.String email, java.lang.Integer salario,
			java.lang.Integer gastosMes, java.lang.String estado) {
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.salario = salario;
		this.gastosMes = gastosMes;
		this.estado = estado;
	}

}